### ISSUE TITLE
Main Effects and Interactions with Categorical Variables

### ISSUE THREAD

**Issue by iekanat** [christophergandrud/simPH#20]
SimPH currently lacks facilities to accomodate categorical variables with multiple categories, which is a common use case.

When categorical variables are used in coxph, the model creates dummies for each of the levels (except the reference level) and these names differ from the original variable name.  This creates problems as the SimPH functions can not match names of dummies to original variables.

I think adding this functionality will add to SimPH's appeal.

**Comment by christophergandrud** [comment]
Thanks for pointing this out. I've just pushed up a slightly modified version (d79ec28d28be0d24d8195434ebca0c5607d2714e) that should work. 

Install it with:

```{S}
devtools::install_github('christophergandrud/simPH')
```

Here is an example: 

```{S}
library(rio)
hmohiv <- import("http://www.ats.ucla.edu/stat/r/examples/asa/hmohiv.csv")

# Create category lables
hmohiv$drug <- factor(hmohiv$drug, labels = c('not treated', 'treated'))

M3 <- coxph(Surv(time,censor) ~ drug*age, data = hmohiv)

# Note: Use relevant coefficient name as shown in model summary, e.g.
# 'drugtreated'.
Sim5 <- coxsimInteract(drug, b1 = "drugtreated", b2 = 'age', X2 = 20:54)
```

Please test it out and see if it works for you.

**Comment by iekanat** [comment]
Thank you Dr. Gandrud

**Comment by iekanat** [comment]
Dr. Gandrud,

I tested the new code. Seems like it is not running correctly. Please find
error messages below.

I suspect it may be a difference in installations as I failed to reproduce
the example code you provided. I am using R on an Ubuntu machine and had to
install R version 3.2.0 (2015-04-16) from repositories to get devtools
working (a problem with openSSL-dev package in earlier versions).

My use case is a categorical variable (3 levels) interacted with a
continuous variable constrained between 0 and 1.

When I try your example code I get the error message:

Error in coxsimInteract(drug, b1 = "drugtreated", b2 = "age", X2 = 20:54) :
  object 'drug' not found

When I try it on my own dataset, I get the error message:
Sim5 <- coxsimInteract(cph_crtv2_3b, b1 = "CCatHIGH", b2 =
'cum.successRate', X2 =seq(0, 1, by=.01), nsim=1000 )
101000 (100%) simulations dropped for having
quantity of interest values: Inf/NA/NaN/>1000000.

To keep extreme values set extremesDrop = FALSE.

Please advise on how to proceed. I want to be helpful.

Best,
Irfan

**Comment by iekanat** [comment]
Oh sorry, I noticed a small mistake in the example code.

Sim5 <- coxsimInteract(M3, b1 = "drugtreated", b2 = 'age', X2 = 20:54)

Let me try to plot it out.

**Comment by iekanat** [comment]
Somehow, the output object is not the same as others of the same class. I
can not plot it.

**Comment by dvdkruijssen** [comment]
Dear dr. Gandrud, is it possible to plot interactions between two categorical variables? A hypothetical example:

M3 <- coxph(Surv(time,censor) ~ drug*gender, data = hmohiv)
Sim5 <- coxsimInteract(drug, b1 = "drugtreated", b2 = 'gendermale')

I would like to plot the interaction between two binary categorical variables. Would this be possible?
