### ISSUE TITLE
coxsimtvc() Broken (1.3.11)

### ISSUE THREAD

**Issue by MetzgerSK** [christophergandrud/simPH#24]
A code update in the newest `simPH` release seems to have broken `coxsimtvc()`.  

- When I run the function's help file's demo code under 1.3.10 (pasted at end for reference), everything works as it should.
- When I run the same code in a fresh R session with 1.3.11 installed, there's new output to the console (see below).  Sim1 is also now an object with 0 observations and 4 variables.
```
Warning messages:
1: Factor `time` contains implicit NA, consider using `forcats::fct_explicit_na` 
2: Factor `time` contains implicit NA, consider using `forcats::fct_explicit_na` 
```
Two of my students are also getting the same error.  (From my quick poking, it looks like the issue may stem from line 50's `merge()`.)  

```
## The relevant chunk from the help file, for reference

# Load Golub & Steunenberg (2007) Data
data("GolubEUPData")

# Load survival package
library(survival)

# Expand data (not run to speed processing time, but should be run)
GolubEUPData <- SurvExpand(GolubEUPData, GroupVar = 'caseno',
                     Time = 'begin', Time2 = 'end', event = 'event')

# Create time interactions
BaseVars <- c('qmv', 'backlog', 'coop', 'codec', 'qmvpostsea', 'thatcher')
GolubEUPData <- tvc(GolubEUPData, b = BaseVars, tvar = 'end', tfun = 'log')

# Run Cox PH Model
M1 <- coxph(Surv(begin, end, event) ~ qmv + qmvpostsea + qmvpostteu +
                coop + codec + eu9 + eu10 + eu12 + eu15 + thatcher +
                agenda + backlog + qmv_log + qmvpostsea_log + coop_log +
                codec_log + thatcher_log + backlog_log,
            data = GolubEUPData, ties = "efron")

# Create simtvc object for Relative Hazard 
Sim1 <- coxsimtvc(obj = M1, b = "qmv", btvc = "qmv_log",
                   tfun = "log", from = 80, to = 2000,
                   Xj = 1, by = 15, ci = 0.99, nsim = 100)
```

**Comment by paulfcwinter** [comment]
Bumping this issue. 

I have the same error when I use simtvc and when designating a factor as the "b" variable in coxsimLinear as well (can post code if required).

**Comment by christophergandrud** [comment]
Thanks for reporting. Solved in https://github.com/christophergandrud/simPH/commit/3b6a557ab339e25c97b488ac2e5b5bcf7f97e4b2

Should be on CRAN soon.
